# Generated by Django 5.2.9 on 2026-01-05 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование блюда')),
                ('description', models.TextField(blank=True, verbose_name='Описание/технология приготовления')),
                ('output_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Выход, кг/шт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно для продажи')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='OverheadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование статьи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('short_name', models.CharField(max_length=10, verbose_name='Сокращение')),
            ],
        ),
        migrations.CreateModel(
            name='CostCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчета')),
                ('portion_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость порции')),
                ('overhead_per_portion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Накладные расходы на порцию')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Полная себестоимость')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.dish', verbose_name='Блюдо')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая цена за ед.')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Минимальный остаток')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.ingredientgroup', verbose_name='Группа')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calc.unit', verbose_name='Единица измерения')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='output_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='calc.unit', verbose_name='Единица выхода'),
        ),
        migrations.CreateModel(
            name='DishComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Количество на одну порцию')),
                ('losses_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент потерь')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='calc.dish', verbose_name='Блюдо')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calc.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'unique_together': {('dish', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='Overhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма, руб.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.overheadcategory', verbose_name='Статья расходов')),
            ],
            options={
                'unique_together': {('category', 'month')},
            },
        ),
    ]
